name = "Select"
uuid = "9af9b3ce-3316-11e9-0fa8-7b2e06453de4"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.1.0"

[deps]
FieldMetadata = "bf96fef3-21d2-5d20-8afa-0e7d4c32a885"

[extras]
FieldDefaults = "49426c49-986f-5969-8844-d5cc96441cfc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["FieldDefaults", "Test"]
