authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
name = "Select"
uuid = "9af9b3ce-3316-11e9-0fa8-7b2e06453de4"
version = "0.1.0"

[deps]
FieldMetadata = "bf96fef3-21d2-5d20-8afa-0e7d4c32a885"
